---
title: "incarceration and supervision"
output: html_document
date: "2023-05-03"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(here)
library(tidyverse)
library(urbnmapr)
library(janitor)
```

## R Markdown



```{r}
Incarceration_and_Supervision <- read_excel(here("Data/Incarceration_and_Supervision.xlsx"))
```

```{r}
states <- get_urbn_map(map = "states", sf = TRUE)
```

```{r}
Incarceration_and_Supervision <- Incarceration_and_Supervision %>% 
  clean_names()
```

```{r}
colnames(Incarceration_and_Supervision)[colnames(Incarceration_and_Supervision) == "state"] ="state_name"

```

```{r}
Incarceration_and_Supervision_map <- left_join(get_urbn_map(map = "states", sf = TRUE),
Incarceration_and_Supervision, by = "state_name")


```
```{r}
Incarceration_and_Supervision_map <- Incarceration_and_Supervision_map %>% 
  filter(state_name != "50 States and D.C. total",
         state_name != "District of Columbia")
```

```{r}
Incarceration_and_Supervision_map_filtered <- Incarceration_and_Supervision_map %>% 
  select(state_name, geometry, federal_prison_rate)
```



```{r}
ggplot()+
  geom_sf(Incarceration_and_Supervision_map,
          mapping = aes(fill = federal_prison_rate), 
          color = "#ffffff")
```

